In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [4]:
# load the dataset
iris = load_iris()
X = iris.data
y = iris.target

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)


# Gaussian Naive Bayes

In [6]:
# Model initialize
gnb = GaussianNB()

# train the model
gnb.fit(X_train,y_train)

# Predict
y_pred = gnb.predict(X_test)

In [8]:
# Model evaluation
print('Accuracy : ', accuracy_score(y_test,y_pred))
print('\nConfusion Matrix :\n',confusion_matrix(y_test,y_pred))
print('\nClassification Report : \n',classification_report(y_test,y_pred))

Accuracy :  1.0

Confusion Matrix :
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Multinomial Naive Bayes

In [9]:
# Model initialize
mnb = MultinomialNB()

# train the model
mnb.fit(X_train,y_train)

# Predict
y_pred = mnb.predict(X_test)

# Model evaluation
print('Accuracy : ', accuracy_score(y_test,y_pred))
print('\nConfusion Matrix :\n',confusion_matrix(y_test,y_pred))
print('\nClassification Report : \n',classification_report(y_test,y_pred))

Accuracy :  0.9

Confusion Matrix :
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]

Classification Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



# Bernoulli Naive Bayes

In [10]:
# Model initialize
bnb = BernoulliNB()

# train the model
bnb.fit(X_train,y_train)

# Predict
y_pred = bnb.predict(X_test)

# Model evaluation
print('Accuracy : ', accuracy_score(y_test,y_pred))
print('\nConfusion Matrix :\n',confusion_matrix(y_test,y_pred))
print('\nClassification Report : \n',classification_report(y_test,y_pred))

Accuracy :  0.3

Confusion Matrix :
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



D:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
