In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
from sklearn.preprocessing import StandardScaler

In [5]:
data = {
    'age':[25,30,40,45],
    'height':[165,149,175,167],
    'weight':[60,70,76,78]
              }
df= pd.DataFrame(data)
df

,age,height,weight
0,25,165,60
1,30,149,70
2,40,175,76
3,45,167,78


In [6]:
scalar = StandardScaler()
scaled_df = scalar.fit_transform(df)
scaled_df

array([[-1.26491106,  0.10599979, -1.57142857],
       [-0.63245553, -1.58999682, -0.14285714],
       [ 0.63245553,  1.16599767,  0.71428571],
       [ 1.26491106,  0.31799936,  1.        ]])

In [7]:
# convert this data into a pandas dataframe
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df

,age,height,weight
0,-1.264911,0.106000,-1.571429
1,-0.632456,-1.589997,-0.142857
2,0.632456,1.165998,0.714286
3,1.264911,0.317999,1.000000


# Min-Max Scalrr

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
data = {
    'age':[25,30,40,45],
    'height':[165,149,175,167],
    'weight':[60,70,76,78]
              }
df1= pd.DataFrame(data)
df1

,age,height,weight
0,25,165,60
1,30,149,70
2,40,175,76
3,45,167,78


In [12]:
scalar1 = MinMaxScaler()
scaled_df = scalar1.fit_transform(df1)
scaled_df

array([[0.        , 0.61538462, 0.        ],
       [0.25      , 0.        , 0.55555556],
       [0.75      , 1.        , 0.88888889],
       [1.        , 0.69230769, 1.        ]])

In [13]:
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df

,age,height,weight
0,0.00,0.615385,0.000000
1,0.25,0.000000,0.555556
2,0.75,1.000000,0.888889
3,1.00,0.692308,1.000000


# Max Abslout Error

In [18]:
from sklearn.preprocessing import MaxAbsScaler

In [19]:
scaler = MaxAbsScaler()
scaled_df = scalar1.fit_transform(df1)
scaled_df

array([[0.        , 0.61538462, 0.        ],
       [0.25      , 0.        , 0.55555556],
       [0.75      , 1.        , 0.88888889],
       [1.        , 0.69230769, 1.        ]])

In [20]:
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df

,age,height,weight
0,0.00,0.615385,0.000000
1,0.25,0.000000,0.555556
2,0.75,1.000000,0.888889
3,1.00,0.692308,1.000000


# Robust Scaler

In [21]:
from sklearn.preprocessing import RobustScaler

In [22]:
scaler = RobustScaler()
scaled_df = scalar1.fit_transform(df1)
scaled_df

array([[0.        , 0.61538462, 0.        ],
       [0.25      , 0.        , 0.55555556],
       [0.75      , 1.        , 0.88888889],
       [1.        , 0.69230769, 1.        ]])

In [23]:
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df

,age,height,weight
0,0.00,0.615385,0.000000
1,0.25,0.000000,0.555556
2,0.75,1.000000,0.888889
3,1.00,0.692308,1.000000
