In [1]:
import numpy as np

In [3]:
a = np.arange(6)

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [6]:
a2.shape

(1, 6)

In [7]:
a.shape

(6,)

In [10]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

In [15]:
empty = np.empty((2,3))

In [16]:
print(empty)

[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]


In [17]:
print(empty[1])

[2.22044605e-016 2.22507386e-308 4.94065646e-324]


In [18]:
even = np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [19]:
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [21]:
lin = np.linspace(0,10,num=10)
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
lin.dtype

dtype('float64')

# Sorting an array

In [23]:
arr = np.array([2,1,15,35,24,66,21,32,25])
arr

array([ 2,  1, 15, 35, 24, 66, 21, 32, 25])

In [27]:
np.sort(arr)

array([ 1,  2, 15, 21, 24, 25, 32, 35, 66])

# Concetation

In [28]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

In [29]:
z = np.concatenate((x,y))

In [30]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

# Indexing and Slicing

In [32]:
w = np.array([1,2,3,4,5,6,7,8])
w

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
w[2:5]

array([3, 4, 5])

In [35]:
w[-4:-2]

array([5, 6])

In [36]:
w[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [37]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
b[0]

array([1, 2, 3, 4])

In [39]:
b[1]

array([5, 6, 7, 8])

In [40]:
b[2]

array([ 9, 10, 11, 12])

In [41]:
b[b<5]

array([1, 2, 3, 4])